allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
  workerd: true
patchedDependencies:
  '@dashcommerce/core@0.1.4': patches/@dashcommerce__core@0.1.4.patch
peerDependencyRules:
  allowedVersions:
    emdash: '0.27.0'
